version: '3'
services:
  spark-master:
    image: jupyter/all-spark-notebook:latest
    container_name: spark-master
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_LOCAL_IP=spark-master
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - "8888:8888"  # Jupyter Notebook UI
      - "8080:8080"  # Spark Master Web UI
    networks:
      - spark-network
    command: start.sh jupyter lab --LabApp.token='' --LabApp.password=''

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
